// Generated by CoffeeScript 1.8.0
var authFP, close, init, insert, java, jdbcJar, plug, select;

java = require('java');

jdbcJar = './plug/plug_api.jar';

java.classpath.push(jdbcJar);

plug = java.newInstanceSync('org.cozy.plug.Plug');

init = function(callback) {
  var timeoutProtect;
  timeoutProtect = setTimeout((function() {
    timeoutProtect = null;
    callback({
      error: 'PlugDB timed out'
    });
  }), 20000);
  plug.plugInit('/dev/ttyACM0', function(err) {
    if (timeoutProtect) {
      clearTimeout(timeoutProtect);
      callback(err);
    }
  });
};

insert = function(ids, callback) {
  var array;
  array = java.newArray('java.lang.String', ids);
  plug.plugInsert(array, function(err) {
    callback(err);
  });
};

select = function(callback) {
  plug.plugSelect(function(err, result) {
    callback(err, result);
  });
};

close = function(callback) {
  plug.plugClose(function(err) {
    callback(err);
  });
};

authFP = function(callback) {
  plug.plugFPAuthentication(function(err, authID) {
    callback(err, authID);
  });
};

exports.init = init;

exports.insert = insert;

exports.select = select;

exports.close = close;

exports.authFP = authFP;
